### ISSUE TITLE
求助构建失败

### ISSUE THREAD

**Issue by MSCMDD** [YidaozhanYa/hexo-theme-stellaris#1]
怎么安装啊？构建失败
报错qwq

**Comment by chiyuki0325** [comment]
@MSCMDD 请提供详细日志

**Comment by MSCMDD** [comment]
ERROR Render HTML failed: index.html
TypeError: Cannot read properties of undefined (reading 'animate')
    at HeaderAvatar (E:\BlogWebsite\new\themes\stellaris\layout\components\sidebar\/header.jsx:9:50)
    at processChild (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\new\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'animate')
    at HeaderAvatar (E:\BlogWebsite\new\themes\stellaris\layout\components\sidebar\/header.jsx:9:50)
    at processChild (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\new\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\new\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\new\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\new\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\new\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)

**Comment by chiyuki0325** [comment]
确定是 bug。
给网站设置一个头像即可。

**Comment by chiyuki0325** [comment]
是默认配置文件 `config.stellaris.yml` 中，我填写出错了一个条目。
在 `    animate: auto # auto, always` 的上一行，增加一个 `  animated_avatar:` 即可。参考最新 commit，已经修复。
