### ISSUE TITLE
更多问题qwq

### ISSUE THREAD

**Issue by MSCMDD** [YidaozhanYa/hexo-theme-stellaris#2]
如果加入了副标题构建则会报错qwq

**Comment by MSCMDD** [comment]
指的是网页副标题

**Comment by chiyuki0325** [comment]
配置文件中的哪项呢

**Comment by chiyuki0325** [comment]
Hexo 配置文件中的 `subtitle` 项测试并无问题

**Comment by MSCMDD** [comment]
那么我应该如何正确的从Stellar过渡到Stallaris呢？
我现在新建一个博客
我的步骤
第一步：
```hexo init```
第二步：
```npm install hexo-renderer-jsx --save```
第三步：
```npm install node-fetch@2 --save```
第四步：
更改根目录配置文件theme为Stellaris
第五步：
```git init```
第六步：
```git submodule add https://github.com/YidaozhanY/hexo-theme-stellaris.git themes/stellaris```
由于网络原因我将其改为了
```git submodule add git@github.com:YidaozhanYa/hexo-theme-stellaris.git themes/stellaris```
可以成功拉取
第七步
```hexo s```
报错
```
ERROR Render HTML failed: index.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\themes\sss\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\themes\sss\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\themes\sss\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\themes\sss\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\themes\sss\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\themes\sss\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\themes\sss\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\themes\sss\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\themes\sss\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\themes\sss\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\themes\sss\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\themes\sss\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\themes\sss\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
```
根据您提供的头像问题
我复制了主题目录的```_config.yml```将其命名为```_config.stellaris.yml```复制到根目录
更改了根目录的``_config.yml```的
```
favicon: https://msc-a.netlify.app/medias/logo.svg
avatar: https://msc-a.netlify.app/medias/logo.svg
```
之后报错信息变为了
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Recent (E:\themes\sss\themes\stellaris\layout\components\widgets\recent.jsx:6:5)
    at SidebarWidgets (E:\themes\sss\themes\stellaris\layout\components\sidebar\sidebar.jsx:111:9)
    at div
    at Widgets
    at Sidebar (E:\themes\sss\themes\stellaris\layout\components\sidebar\sidebar.jsx:12:5)
    at aside
    at div
    at body
    at html
    at Layout (E:\themes\sss\themes\stellaris\layout\layout.jsx:6:5)
ERROR Render HTML failed: index.html
Error: Cannot find module './null/script.jsx'
Require stack:
- E:\themes\sss\themes\stellaris\layout\components\plugins\comments\script.jsx
- E:\themes\sss\themes\stellaris\layout\components\scripts.jsx
- E:\themes\sss\node_modules\hexo-renderer-jsx\lib\compile.js
- E:\themes\sss\node_modules\hexo-renderer-jsx\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Function.Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at CommentsScript (E:\themes\sss\themes\stellaris\layout\components\plugins\comments\/script.jsx:3:27)
    at processChild (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\themes\sss\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\themes\sss\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\themes\sss\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\themes\sss\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\themes\sss\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\themes\sss\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\themes\sss\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\themes\sss\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\themes\sss\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\themes\sss\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\themes\sss\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\themes\sss\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\themes\sss\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
Unhandled rejection Error: Cannot find module './null/script.jsx'
Require stack:
- E:\themes\sss\themes\stellaris\layout\components\plugins\comments\script.jsx
- E:\themes\sss\themes\stellaris\layout\components\scripts.jsx
- E:\themes\sss\node_modules\hexo-renderer-jsx\lib\compile.js
- E:\themes\sss\node_modules\hexo-renderer-jsx\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Function.Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at CommentsScript (E:\themes\sss\themes\stellaris\layout\components\plugins\comments\/script.jsx:3:27)
    at processChild (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\themes\sss\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\themes\sss\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\themes\sss\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\themes\sss\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\themes\sss\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\themes\sss\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\themes\sss\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\themes\sss\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\themes\sss\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\themes\sss\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\themes\sss\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\themes\sss\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\themes\sss\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\themes\sss\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
```

**Comment by MSCMDD** [comment]
看起来问题没有那么大了

**Comment by MSCMDD** [comment]
关于副标题问题我已经找到是如何触发的了
在Stellar主题中，副标题允许  ```A | B```
这样就可以有一个上下轮播的副标题
如果在Stellaris中这样做的话，会报错

**Comment by chiyuki0325** [comment]
@MSCMDD 本主题是从相对较旧的 Stellar 版本 fork 而来的（大概是 15 版本那时候），功能缺失很正常。
方便提供一下具体报错日志嘛？

**Comment by MSCMDD** [comment]
ERROR Render HTML failed: index.html
ReferenceError: Fragment is not defined
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\themes\stellaris\layout\components\sidebar\/title.jsx:11:30
    at HeaderTitle (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\themes\stellaris\layout\components\sidebar\/title.jsx:19:18)
    at processChild (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
Unhandled rejection ReferenceError: Fragment is not defined
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\themes\stellaris\layout\components\sidebar\/title.jsx:11:30
    at HeaderTitle (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\themes\stellaris\layout\components\sidebar\/title.jsx:19:18)
    at processChild (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)

**Comment by MSCMDD** [comment]
加油，达瓦里氏！~我看好你

**Comment by chiyuki0325** [comment]
已修复

**Comment by MSCMDD** [comment]
问题依旧qwq
```
ERROR Render HTML failed: index.html
Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
    at assertValidProps (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:1841:13)
    at ReactDOMServerRenderer.renderDOM (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4231:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3802:21)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)
Unhandled rejection Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
    at assertValidProps (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:1841:13)
    at ReactDOMServerRenderer.renderDOM (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4231:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3802:21)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:478:21)

Unhandled rejection Error: ReadNext(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\util.js:16:23)
    at E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\BlogWebsite\website\mscmdd.github.io\YidaozhanY\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
