### ISSUE TITLE
hexo -g 报错

### ISSUE THREAD

**Issue by RamSong** [YidaozhanYa/hexo-theme-stellaris#4]
hexo: 6.3.0
hexo-cli: 4.3.1
node: 14.21.3

```
PS C:\Users\Administrator\Desktop\blog> hexo g
INFO  Validating config
INFO  Welcome to Stellaris 1.1.0
DOCS  https://blog.yidaozhan.top/
REPO  https://github.com/YidaozhanYa/hexo-theme-stellaris.git

INFO  Start processing
INFO  Files loaded in 1.76 s
ERROR Render HTML failed: index.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR Render HTML failed: 404.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: ReadNext(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:465:10)
    at resume_ (internal/streams/readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
ERROR Render HTML failed: archives/index.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR Render HTML failed: archives/2023/index.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR Render HTML failed: archives/2023/08/index.html
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
ERROR
Error: HeaderAvatar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\Administrator\Desktop\blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at render (C:\Users\Administrator\Desktop\blog\node_modules\hexo-renderer-jsx\lib\compile.js:21:43)
    at _View._compiled (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\Administrator\Desktop\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Administrator\Desktop\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
```

**Comment by chiyuki0325** [comment]
需要设置头像。
本主题毕竟只是我改来自用，有些适配的毛病正常。
欢迎 pr。
